exports.cekResi = require('./cekResi')
exports.downloader = require('./downloader')
exports.translate = require('./translate')
//exports.edukasi = require('./edukasi')
//exports.igstalk = require('./igstalk')
